import { Level, UniverseType } from './types';

// Palette mapping table
export const COLOR_PALETTE: { [key: string]: string } = {
  'W': '#FFFFFF', // White
  'K': '#1A1525', // Black/Dark Charcoal
  'R': '#EF4444', // Red (Angry bird body / shield crown)
  'Y': '#FBBF24', // Yellow (Sun, Bird beak, Homer skin)
  'G': '#22C55E', // Green (Shield stripes, leaves)
  'B': '#3B82F6', // Blue (Mug glass)
  'O': '#F97316', // Orange (Betis crown, Beer liquid)
  'H': '#8B5CF6', // Purple/Violet
  'M': '#D946EF', // Fuchsia/Pink
  'S': '#06B6D4', // Cyan
  'D': '#78350F', // Dark Brown (Branch / Table / Homer shadow)
  'P': '#F472B6', // Light pink
  'C': '#94A3B8', // Slate grey (Cloud)
};

// Universe associations
export const UNIVERSE_LEVELS: Record<UniverseType, number[]> = {
  'EASY': [1, 2],
  'DENSE': [3, 4],
  'HARD': [5, 6],
  'SUPER_HARD': [7, 8],
};

export const ALL_LEVELS: Level[] = [
  {
    id: 1,
    name: "Mushroom Kingdom",
    gridWidth: 32,
    gridHeight: 32,
    layout: [
      "................................",
      "................................",
      "............WWWWWWWW............",
      "..........WWWWWWWWWWWW..........",
      "........WWWWWWWWWWWWWWWW........",
      ".......WWWWWWWWWWWWWWWWWW.......",
      "......WWWWWWWWWWWWWWWWWWWW......",
      ".....WWWWWWWWWWWWWWWWWWWWWW.....",
      ".....WWWWWWWWWWWWWWWWWWWWWW.....",
      "....WWWWWWWWWWWWWWWWWWWWWWWW....",
      "....WWWWWWWWWWWWWWWWWWWWWWWW....",
      "....WWWWWWWWWWWWWWWWWWWWWWWW....",
      "....WWWWWWWWWWWWWWWWWWWWWWWW....",
      ".....WWWWWWWWWWWWWWWWWWWWWW.....",
      "......WWWWWWWWWWWWWWWWWWWW......",
      ".......WWWWWWWWWWWWWWWWWW.......",
      "........WWWWWWWWWWWWWWWW........",
      "..........WWWWWWWWWWWW..........",
      "............WWWWWWWW............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "............MMMMMMMM............",
      "................................",
      "................................"
    ]
  },
  {
    id: 2,
    name: "Incognito",
    gridWidth: 38,
    gridHeight: 38,
    layout: [
      "......................................",
      "......................................",
      "..............WWWWWWWWWW..............",
      ".............WWWWWWWWWWWW.............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      "............WWWWWWWWWWWWWW............",
      ".......WWWWWWWWWWWWWWWWWWWWWWWW.......",
      ".......WWWWWWWWWWWWWWWWWWWWWWWW.......",
      ".......WWWWWWWWWWWWWWWWWWWWWWWW.......",
      "......................................",
      "......................................",
      "..........WWWWWWWW....WWWWWWWW........",
      ".........WWWWWWWWWW..WWWWWWWWWW.......",
      "........WWWW....WWWWWWWW....WWWW......",
      "........WWWW....WWWWWWWW....WWWW......",
      "........WWWW....WWWWWWWW....WWWW......",
      "........WWWW....WWWWWWWW....WWWW......",
      ".........WWWWWWWWWW..WWWWWWWWWW.......",
      "..........WWWWWWWW....WWWWWWWW........",
      "......................................",
      "......................................",
      "......................................"
    ]
  },
  {
    id: 3,
    name: "Crown Shield",
    gridWidth: 36,
    gridHeight: 36,
    layout: [
      ".................OO.................",
      "................OOOO................",
      "...............OOOOOO...............",
      "..........OO..OOOOOOOO..OO..........",
      ".........OOOO.OOOOOOOO.OOOO.........",
      "........OOOOOOOOOOOOOOOOOOOO........",
      ".......OOOOOOOOOOOOOOOOOOOOOO.......",
      "........OOOOOOOOOOOOOOOOOOOO........",
      ".........OOOOOOOOOOOOOOOOOO.........",
      "..........OOOOOOOOOOOOOOOO..........",
      "...........RRRRRRRRRRRRRR...........",
      "..........RRRRRRRRRRRRRRRR..........",
      ".........RRRRRRRRRRRRRRRRRR.........",
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WGGWGGWGGWGGWGGWGGWGGWGGWGGWGGWGGWGW",
      ".WGGWGGWGGWGGWGGWGGWGGWGGWGGWGGWGGW.",
      "..WGGWGGWGGWGGWGGWGGWGGWGGWGGWGGW...",
      "...WGGWGGWGGWGGWGGWGGWGGWGGWGGW.....",
      "....WGGWGGWGGWGGWGGWGGWGGWGGW.......",
      ".....WGGWGGWGGWGGWGGWGGWGGW.........",
      "......WGGWGGWGGWGGWGGWGGW...........",
      ".......WGGWGGWGGWGGWGGW.............",
      "........WGGWGGWGGWGGW...............",
      ".........WGGWGGWGGW.................",
      "..........WGGWGGW...................",
      "...........WGGW.....................",
      "............WW......................"
    ]
  },
  {
    id: 4,
    name: "3D Cube",
    gridWidth: 36,
    gridHeight: 36,
    layout: [
      ".................WW.................",
      "................WWWW................",
      "...............WWWWWW...............",
      "..............WWWWWWWW..............",
      ".............WWGWWGWWWW.............",
      "............WWGGWWGGWWWW............",
      "...........WWGGGGWWGGGGWW...........",
      "..........WWGGGGGGWWGGGGGG..........",
      ".........WWGGGGWWGGWWGGGGWW.........",
      "........WWGGGGWWGGGGWWGGGGWW........",
      ".......WWGGGGWWGGWWGGWWGGGGWW.......",
      "......WWGGGGWWGGWWWWGGWWGGGGWW......",
      ".....WWGGGGWWGGWWWWWWGGWWGGGGWW.....",
      "....WWGGGGWWGGWWWWWWWWGGWWGGGGWW....",
      "....WWWWWWWWGGWWWWWWWWGGWWWWWWWW....",
      "....WWWWWWWWGGWWWWWWWWGGWWWWWWWW....",
      ".....WWGGGGWWGGWWWWWWGGWWGGGGWW.....",
      "......WWGGGGWWGGWWWWGGWWGGGGWW......",
      ".......WWGGGGWWGGWWGGWWGGGGWW.......",
      "........WWGGGGWWGGGGWWGGGGWW........",
      ".........WWGGGGWWGGWWGGGGWW.........",
      "..........WWGGGGGGWWGGGGGG..........",
      "...........WWGGGGWWGGGGWW...........",
      "............WWGGWWGGWWWW............",
      ".............WWGWWGWWWW.............",
      "..............WWWWWWWW..............",
      "...............WWWWWW...............",
      "................WWWW................",
      ".................WW................."
    ]
  },
  {
    id: 5,
    name: "Sunset Cardinal Bird",
    gridWidth: 36,
    gridHeight: 36,
    layout: [
      "......CCCCCCC...................YYYY",
      "....CCCCCCCCCCC...............YYYYYY",
      ".....CCCCCCCCC...............YYYYYYY",
      "..............................YYYYYY",
      "................................YYYY",
      "............RRRRRRRRRRR.............",
      "..........RRRRRRRRRRRRRRR...........",
      ".........RRRRRRRRRRRRRRRRR..........",
      "........RRRRKKRRRRRKKRRRRRR.........",
      "........RRRRKKRRRRRKKRRRRRR.........",
      "........RRRRRRRRRRRRRRRRRRR.........",
      "........RRRRRRRYYYYYRRRRRRR.........",
      "........RRRRRRYYYYYYYRRRRRR.........",
      "........RRRRRRRYYYYYRRRRRRR.........",
      "........RRRRRRRRRRRRRRRRRRR.........",
      "........RRRRRRRRRRRRRRRRRRR.........",
      ".........RRRRRRRRRRRRRRRRR..........",
      "..........RRRRRRRRRRRRRRR...........",
      "...........RRRRRRRRRRRRR............",
      "............RRRPPPRRRRR.............",
      "............RRPPPPPRRR..............",
      "............RRPPPPPRR............G..",
      "............RRPPPPPRR...........GGG.",
      ".............RRYYYRR...........GGGGG",
      ".............RR.RR..............GGG.",
      ".............YY.YY..................",
      ".......DDDDDDDDDDDDDDDDDDDD..........",
      "....DDDDDDDDDDDDDDDDDDDDDDDDDDD.....",
      "...................................."
    ]
  },
  {
    id: 6,
    name: "Classic Grid Mania",
    gridWidth: 32,
    gridHeight: 30,
    layout: [
      "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
      "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
      "................................",
      "....WWWWWWWW........WWWWWWWW....",
      "....WWWWWWWW........WWWWWWWW....",
      "....WW....WW........WW....WW....",
      "....WW....WW........WW....WW....",
      "....WWWWWWWW........WWWWWWWW....",
      "....WWWWWWWW........WWWWWWWW....",
      "................................"
    ]
  },
  {
    id: 7,
    name: "Homer drinking Beer",
    gridWidth: 40,
    gridHeight: 40,
    layout: [
      "........................................",
      "................KKKKK...................",
      "..............KKYYYYYKK.................",
      "............KKYYYYYYYYYKK...............",
      "............KKYYYYKKKKYYKK..............",
      "..........KKYYYYYKK..KKYKK..............",
      ".........KKYKKYKK....KKYKK..............",
      ".........KKYKKK......KKYKK..............",
      ".........KKYKK.......KKYKK..............",
      ".........KKYKK.......KKYKK..............",
      ".........KKYKKYKK...KKYKK...............",
      ".........KKYKKKYYYYKKYKK................",
      "..........KKYKKYYYYKKYKK................",
      "...........KKYYYYKKKKKK.................",
      "..........KKWWWWWWWWWWKK................",
      ".........KKWWKWWWWKWWWWKK...............",
      ".........KKYWKKWWKKWWWWKK...............",
      "........KKYWWWWWWWWWWWWKK...............",
      "........KKYKKWWWWWWKWWKK................",
      "........KKYKKKKKKKKKKKK.................",
      "........KKYKKDDDDDDDKK..................",
      "........KKYKDDDDDDDDDKK.KKKKKKKKKKKKKKW.",
      "........KKKDDDKKDKKDDDKKWWWWWWWWWWWWWWK.",
      "..........KDDDKKKKKDDDKKWWKKKKKKKKKKWWK.",
      "..........KKDDDDDDDDDKKWWKK........KKWK.",
      "...........KKDDDDDDDKKWWKK.........KKWK.",
      "............KKKKKKKKKWWKK..........KKWK.",
      "..............KKKKKWWKK............KKWK.",
      ".............KKYYYYKWWKK...........KKWK.",
      "............KKYYYYYYKWWKK..........KKWK.",
      "...........KKYYYYYYYYKWWKK.........KKWK.",
      "..........KKYYYYYYYYYYKWWKK........KKWK.",
      "..........KKYYYYYYYYYYKWWKKKKKKKKKKKKK..",
      ".........KKYYYYYYYYYYYYKKKWWWWWWWWWKK...",
      "........KKKYYYYYYYYYYYYYKKKKKKKKKKKK....",
      "........KKWWWWWWWWWWWWWWWWKK............",
      "........KKWWWWWWWWWWWWWWWWKK............",
      ".........KKKKKKKKKKKKKKKKKK............."
    ]
  },
  {
    id: 8,
    name: "Super Hard Geometry",
    gridWidth: 32,
    gridHeight: 32,
    layout: [
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "R..R..R..R..R..R..R..R..R..R..R.",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
      "M..M..M..M..M..M..M..M..M..M..M.",
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
      "Y..Y..Y..Y..Y..Y..Y..Y..Y..Y..Y.",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "G..G..G..G..G..G..G..G..G..G..G.",
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
      "B..B..B..B..B..B..B..B..B..B..B.",
      "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
      "S..S..S..S..S..S..S..S..S..S..S.",
      "................................",
      "....WW..WW..WW....WW..WW..WW....",
      "....WW..WW..WW....WW..WW..WW....",
      "....KK..KK..KK....KK..KK..KK....",
      "................................"
    ]
  }
];
